### ISSUE TITLE
Suggestion: Article on CDNs like BitMitigate/Cloudflare for DDOS protection

### ISSUE THREAD

**Issue by AndrewBHolder** [LukeSmithxyz/landchad#112]
Seeing as DDOSing is the number one enemy of small websites and aspiring Landchads, I think mentioning them in an article or its own separate article is warranted.

From what I understand, BitMitigate is Epik's answer to Cloudflare, and is apparently better when hosting free speech stuff when compared to Cloudflare.

Other DDOS prevention methods would be nice to learn about as well. I don't want my own XMPP server to suffer downtime from some angry guy with a botnet.

**Comment by LukeSmithxyz** [comment]
I'm not familiar with them. I'll go ahead and say that I will not approve articles that endorse the use of Cloudflare, however if BitMitigate or something else is good, that sounds fine to me.

We might also want other articles about preventing DDOS and other troll/hack attacks by tweaking some other settings. Nginx has some mitigation settings that can be used.

**Comment by phirecc** [comment]
Cloudflare is surprisingly pretty good when it comes to not censoring
people and doing what they're supposed to. Settings may or may not help
depending on the type of attack but generally won't protect you. But to
be honest most people won't have to worry about DDoS attacks (even luke
who is pretty popular and "controversial" hasn't had problems afaik).
You should tackle such problems as they arrive (on the rare chance that
they do).

**Comment by termermc** [comment]
It's important to mention mitigation you can do on the server side first. For static sites, the nginx mitigations will do almost nothing, except maybe the concurrent IP limiting. It's better to configure it with other tools, although I'm not as familiar with them.
As for Cloudflare, it's a bad company, not just because of it deplatforming, but also that all traffic passes through it along with traffic on basically the majority of websites now. BitMitigate I have tried myself, and at least in 2018, it was very slow, but I don't know about now. What I do know is that they still have the same technical problem, that is having all traffic pass through them. If you need it, maybe it's fine but I don't like those services very much at all for that reason.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
