### ISSUE TITLE
benefit over using an vps/root vs webhosting

### ISSUE THREAD

**Issue by gitlerat** [LukeSmithxyz/landchad#125]
Hi,

For Website & own Mail - you can get this here in europa for 2€/mo with webhosting. Included is 50GB of Space, 1 Domain, SSH and SSL Cert and unlimited bandwidth.

If I compare that to vultr i get for 3,5/mo€ 
10 GB SSD space
1 CPU
512 MB
0.50 TB bandwidth

So just for a getting a Internet Landlord, I feel a webhosting would be better. For sure most services like nextcloud and so on will not be possible. 

I am writing this because I am a beginner and want to ask if I am wrong with this statement (for learning purposes).

Also with webhosting I dont have to worry about security or updates. I want to know the benefits of using a vps.

**Comment by termermc** [comment]
You have more control on a VPS and more dedicated resources, as well as the ability to install more things

**Comment by artur-borys** [comment]
>I want to know the benefits of using a vps.

You can use VPS for more things, you can install a VPN to share a network with friends and family in a secure way or access internet securely over unprotected WiFi networks.

>Also with webhosting I dont have to worry about security or updates

Well, you have to worry if the service provider worries enough to provide a good security and make regular updates on their site. If you have a VPS, you can install updates whenever you want (event automate it), and in terms of security - it's probably a good idea to put a firewall in front of your VPS. Many VPS providers offer firewall, or you can use `ufw` and only open those ports that are necessary to access from the outside - HTTP(s) and mail ports. You can access SSH via VPN or at least use other than standard port 22. I have changed the default port on mine server and had no one trying to break in since then
