### ISSUE TITLE
Consider switching domain registrar from Epik Inc. to Njalla

### ISSUE THREAD

**Issue by fraxgut** [LukeSmithxyz/landchad#268]
I recommend that we consider switching our domain registrar from Epik Inc. to Njalla (njal.la).

Recently, Epik Inc. has been facing a company crisis due to financial issues and have been accused of scamming their customers (I've personally faced issues myself registering new domains recently too). Evidence of this can be found on Twitter (https://twitter.com/EpikDotCom) and TrustPilot (https://www.trustpilot.com/review/epik.com).

In light of this, I suggest we switch to a more reliable domain registrar like Njalla, or other similar privacy-focused domain registrars. This will improve the financial safety and security of people following LandChad guides.

**Comment by termermc** [comment]
Njalla is not a good alternative to a mainstream registrar because you don't own the domain, they own it and let you manage it. When you own a domain through a normal registrar, you have certain rights given to you by the ICANN that allow you to transfer at will, make disputes, etc. With Njalla, they own the domain and you have less control over it. Also, by virtue of them owning the domains, they have a unique liability burden which makes them a lot more particular. For this reason, they're primarily a privacy registrar, not a free speech registrar.

**Comment by LukeSmithxyz** [comment]
Yeah Epik has to go now. They have massive delays in registering delays and apparently can't barely do basic things. A million things wrong with them.

Njal.la is fine to recommend, but as stated above, their method of registering domains may be unique and beneficial, but still poses potential risks of losing domains (since you don't legally own them). Although I don't want to recommend a now singularly bad registrar like Epik, there is no exceptional reason to rely singularly on Njal.la eternal benignity either.

So a more conventional and vetted registrar might be good, but few immediately come to mind.

When Epik was hacked, I did change a lot of the verbiage to not specifically recommend them without alternatives, although we still have the screencaps from setting sights up with them as representative of others.

**Comment by LukeSmithxyz** [comment]
Although I don't have a singular recommendation to replace it, I've gone ahead and purged mentions of Epik from the site to avoid these issues. On the first page I just list common registrars that I've had some experience with and also mention Njal.la.
