### ISSUE TITLE
Recommending that people disable their firewall

### ISSUE THREAD

**Issue by uranderu** [LukeSmithxyz/landchad#3]
I was reading the webserver tutorial on the website and was quite surprised to read that you "recommend this in 99% of the cases.". I personally find it dangerous to propose to people who have little experience in this sector of IT to "recommend to just disable the firewall, because it is easier.". This is just very bad practice in my opinion and I am curious to know why you would recommend this.

**Comment by LukeSmithxyz** [comment]
In "99% of the cases" it will only cause user frustration for an illusion of security. This is a site for tutorials about setting up web services and I don't want to have to nag people all the time and in every article about enabling this or that port that they need for whatever service they're going to be installing.

Vultr is pretty irregular in having a preinstalled firewall nowadays (this is new within the past month or so). I can tell from the emails I get that this is a huge confusion to people. I plan on having an article on firewalls, but I would rather this not be something of constant issue in every other article. If you take issue with my categoricalness of dismissing firewalls in the text, that's fine, I might remove it since I don't want extra security to sound "uncool."

**Comment by uranderu** [comment]
Right, I can get into that. But I would just advise wording it differently. Ie. "Generally it is not recommended to disable your firewall, but for the purpose of this tutorial, it is easier to disable it. In the feature, we'll have a dedicated article on how to correctly set up a firewall."
