### ISSUE TITLE
Claiming Irc servers topic

### ISSUE THREAD

**Issue by Juliaria08** [LukeSmithxyz/landchad#31]
I am thinking of doing an article, it will guide on how to setup a irc server using Inspircd ( as irc server ) and Atheme ( for services, NickServ, ChanServ, etc..)

**Comment by paniash** [comment]
That sounds great!

**Comment by oidz1234** [comment]
To piggy back on this, would we need something on IRC bouncers? Perhaps a way to set up a really simple bouncer like https://www.blatech.co.uk/l_bratch/blabouncer? Almost mandatory nowadays with IRC IMO.

**Comment by Juliaria08** [comment]
The tutorials needed to use Debian 10 as a base? Just to confirm the download of a vm localy, i quite like self hosting and i have some things public

**Comment by termermc** [comment]
I actually started writing an article on this this morning, not realizing you had already claimed it. Since I have already written a great deal of the article, perhaps there could be multiple options?

I'm writing mine based on Ergo (formerly Oragono), which is an IRCd written in Go that's easy to configure, and includes services like ChanServ, NickServ, HistServ, and HostServ all built-in, so nothing else has to be setup. It also includes WebSockets support, so webclients can easily be setup for it without any extra hassle. I think it would be a better fit for this than an IRCd that requires much more setup.

I have also been using it for my friends and I for over a year, so I have a great deal of experience with it.

**Comment by Juliaria08** [comment]
I can let you post it as i didnt start writing

**Comment by Juliaria08** [comment]
I had my setup working but i think someone got the link pw for one of the servers... I think i leaked on a forum when asking for help
