### ISSUE TITLE
Suggestion: Approx platform size and RAM consumption

### ISSUE THREAD

**Issue by craxed** [LukeSmithxyz/landchad#54]
Adding approx platform size and RAM consumption in each article under "Build your own platform!". 
Each platform have its own RAM usage and disk usage. For limited size servers, this would be helpful.

**Comment by LukeSmithxyz** [comment]
A good idea. People who host the listed services frequently should feel free to volunteer their footprints. For some things, I'm sure it varies a lot too.

**Comment by phirecc** [comment]
I guess we could collect here, then figure out how to format and add it to articles.
Gitea takes around 230MB for me.
Miniflux (which I might write an article for in the future) takes 35MB, its postgres server 80MB.

To easily see ram usage per user (assuming you run services under separate users), you can use `smem -uk`, using PSS would be most fitting I suppose. Measuring RAM consumption is not as easy as one might think on Linux because of shared libraries (https://stackoverflow.com/questions/22372960/is-this-explanation-about-vss-rss-pss-uss-accurate).

**Comment by termermc** [comment]
Ergo (IRC server) takes around 10mb of RAM for me. This is with around 30 clients connected, maybe more.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by wdunkelheit** [comment]
Pleroma can vary in memory usage based on how busy the instance is. But IIRC from playing with it in the past it never exceeded 300MB for a bare instance.

**Comment by uranderu** [comment]
I like the idea a lot. But sometimes it is a tough one because you are dealing with a lot of variable here :P ie Distro, Virtualization (Yes/no? Containers or fully-fledged VM's?), etc.

**Comment by termermc** [comment]
Assuming this is on a VPS from Vultr, it's a full VM using KVM, I believe. If you're talking about virtualization on the application side, according to the submission rules, none of the tutorials should be using virtualization/containers such as Docker, so that shouldn't factor into it at all.
If things are running on a KVM instance like with Vultr, Linode, DigitalOcean, etc, it should behave normally. The only real variable on the server-side is how much swap is installed, but that's still not a huge problem, usually it's a gigabyte or two, almost never more than the amount of RAM.
The amount of RAM applications themselves use will always been variable of course, but guidance on how much they typically use is pretty easy to establish on most things, provided that you explain your environment and use-case. If you are running a server and 5-10 people use it, most likely the RAM usage in such a use-case would be representative of what most people following the tutorial will be experiencing.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by binex-dsk** [comment]
> If you are running a server and 5-10 people use it, most likely the RAM usage in such a use-case would be representative of what most people following the tutorial will be experiencing.

Well that's pretty much exactly my case. Here's what I got:
- Synapse: 200-400 MB while idle
- Invidious: ~300 MB
- Libr*ddit: 180 MB
- Gitea: 100-150 MB; can destroy CPU when lots of traffic, make sure to install fail2ban
- Peertube: 130 MB, sometimes goes up during traffic
- Uwsgi (SearX): 100 MB
- Prosody: 10-20 MB
- Nginx: 20-30 MB
- Agate (Gemini), Mail server (Postfix, OpenDKIM, Spamassassin, Dovecot), Filtron (bot filter for searx): Literally nothing
